version: "3"

services:
    php:
        build: .
        volumes:
            - ..:/workspace:cached
        ports:
            # For use with PHP (e.g. `php -S localhost:8080`)
            - "8000:8000"
        command: sleep infinity
    mariadb:
        image: mariadb:10.4
        expose:
            # Expose mariadb port to php service (Access as hostname "mariadb" from within php container)
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        expose:
            - "8080"
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
        restart: always
        ports:
            - "8080:80"
